database:
  db: gearz_test
  host: one.tbnr.pw
  port: 27017
announcer:
  enabled: true
channels:
  enabled: false
  list:
    - default
    - staff
formatting:
  default:
    format: "%prefix% %player%%suffix%: %message%"
    permission: ""
    default: true
    filter: true
  staff:
    format: "&0[&1Staff&0] &c%player%&f: &a%message%"
    permission: "gearz.modbroadcast"
    default: false
    filter: false
irc:
  name: TBNRBot
  server: irc.esper.net
  login: tbnr
  enabled: false
  printout: false
  format: "[%server%]<%sender%>: %message%"
friends:
  enabled: true
