formats:
  friend-add: "&cYou have added &4<player>&c as a friend."
  friend-remove: "&cYou have removed &4<player>&c as a friend."
  friend-remove-victim: "&4<player>&c has removed you as a friend."
  friend-already: "&cThat player is already your friend."
  friend-request-received: "&3You received a friend request from &6<player>. &9Use &6/friend add <player>&9 to add them."
  friend-no-request: "&cYou do not have a friend request from that player!"
  friend-already-request: "&cYou have already sent a request to that player!"
  friend-deny: "&cYou denied &4<player>&c's friend request."
  friend-need-request: "&cFriend request sent!"
  friend-not: "&cThat player is not your friend."
  friend-header: "&cCurrently on page &4<page>&6 of &4<max>&c of friends."
  friend-requests-header: "&cCurrently on page &4<page>&6 of &4<max>&c of friend requests."
  friend-online: "&3<player>&7 is &6ONLINE&7 on &9<server>."
  friend-offline: "&3<player>&7 is &4OFFLINE."
  friend-request: "&6Request from &3<player>&6."
  friend-null: "&cThat player does not exist, or is not online."
  friend-self: "&cYou can not do that to your self!"
  friend-usehelp: "&cBad arguments! Use &4/friend help"
  friends-help: "&3<key> &7- &6<value>"
  friends-help-header: "&3&lFriends Help"
  friend-join: "&c<player>&6 is on &c<server>&6, attempting to connect you now."
  friend-join-bad: "&cUnable to connect to that friend's server!"
  friend-same-server: "&cYou are on the same server as that player!"
  page-null: "&cThat page does not exist!"
  not-a-number: "&cThat's not a number!"