formats:
  no-permissions: "&cNo permission."
  invalid-args: "&cYou have supplied invalid argumnets."
  few-args: "&cYou have supplied too few arguments."
  many-args: "&cYou have supplied too many arguments."
  wrong-target: "&cYou can't execute this command!"
  dhoe: "&bThe diamond selection hoe!"
  daxe: "&bThe diamond region selector!"
  gshovel: "&6The golden completion stick!"
  name-prompt: "&aPlease type the name of the arena into your chat."
  author-prompt: "&aPlease type the author (group name or ingame name) into your chat."
  description-prompt: "&aPlease type the short description of this arena."
  select-prompt: "&aPlease use the diamond axe to select the area for this arena. Don't cut anything off, or that will not be placed when the game starts! Hit the golden shovel when you're complete."
  field-prompt: "&aPlease select all the &c<field>&a and hit the golden shovel to finish setup."
  completed: "&aThe arena setup is complete. Type /back <phase> to return to setting up something, /clear <phase> to clear and return to that phase, and /done to upload the map to the database."
  cannot-complete: "&cYou can't save this arena now!"
  saved: "&aThe arena has been saved."
  failed-save: "&cThe arena failed to save."
  selected: "&aPoint selected (&c<count>&a)"
  blocks-added: "&aAdded &c<num>&a points to the current field using skull selectors."
  complete-fail: "&cYou need to select two points!"
  regions-prompt: "&aPlease use the diamond axe to select an area to add a region to the field: &c<field>"